export const GET_ALL_GAMES = 'GET_ALL_GAMES';
export const GET_ALL_GAMES_ERROR = 'GET_ALL_GAMES_ERROR';
export const GET_GAME_DETAILS = 'GET_GAME_DETAILS';
export const GAME_DETAILS_ERROR = 'GAME_DETAILS_ERROR';
